//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RafeTale.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibraryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibraryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RafeTale.Application.Resources.LibraryStrings", typeof(LibraryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute your power and integrate your background legacy.
        /// </summary>
        public static string Abilities_Subtitle {
            get {
                return ResourceManager.GetString("Abilities_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability Scores.
        /// </summary>
        public static string Abilities_Title {
            get {
                return ResourceManager.GetString("Abilities_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrobatics.
        /// </summary>
        public static string Acrobatics {
            get {
                return ResourceManager.GetString("Acrobatics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Handling.
        /// </summary>
        public static string AnimalHandling {
            get {
                return ResourceManager.GetString("AnimalHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcana.
        /// </summary>
        public static string Arcana {
            get {
                return ResourceManager.GetString("Arcana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athletics.
        /// </summary>
        public static string Athletics {
            get {
                return ResourceManager.GetString("Athletics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Library.
        /// </summary>
        public static string Back_LibraryBtn {
            get {
                return ResourceManager.GetString("Back_LibraryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Bonuses.
        /// </summary>
        public static string Background_Bonus {
            get {
                return ResourceManager.GetString("Background_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backgrounds.
        /// </summary>
        public static string Background_Lib {
            get {
                return ResourceManager.GetString("Background_Lib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore character backgrounds and their origin benefits..
        /// </summary>
        public static string Background_Lib_Description {
            get {
                return ResourceManager.GetString("Background_Lib_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your background allows you to apply a +2 and +1 only to:.
        /// </summary>
        public static string BackgroundASI_HelpText {
            get {
                return ResourceManager.GetString("BackgroundASI_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to backgrounds.
        /// </summary>
        public static string BackgroundCodex_BackToList {
            get {
                return ResourceManager.GetString("BackgroundCodex_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading backgrounds....
        /// </summary>
        public static string BackgroundCodex_Loading {
            get {
                return ResourceManager.GetString("BackgroundCodex_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backgrounds.
        /// </summary>
        public static string Backgrounds_Label {
            get {
                return ResourceManager.GetString("Backgrounds_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to based on.
        /// </summary>
        public static string BasedOn {
            get {
                return ResourceManager.GetString("BasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Feat.
        /// </summary>
        public static string Btn_ChooseFeat {
            get {
                return ResourceManager.GetString("Btn_ChooseFeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Now.
        /// </summary>
        public static string Btn_ClaimSelections {
            get {
                return ResourceManager.GetString("Btn_ClaimSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understood.
        /// </summary>
        public static string Btn_Confirm {
            get {
                return ResourceManager.GetString("Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Path.
        /// </summary>
        public static string Btn_ConfirmClass {
            get {
                return ResourceManager.GetString("Btn_ConfirmClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit Level Up.
        /// </summary>
        public static string Btn_ConfirmLevelUp {
            get {
                return ResourceManager.GetString("Btn_ConfirmLevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge Legend.
        /// </summary>
        public static string Btn_FinishCharacter {
            get {
                return ResourceManager.GetString("Btn_FinishCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Stats.
        /// </summary>
        public static string Btn_IncreaseStats {
            get {
                return ResourceManager.GetString("Btn_IncreaseStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEVEL UP.
        /// </summary>
        public static string Btn_LevelUp {
            get {
                return ResourceManager.GetString("Btn_LevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Btn_NextStep {
            get {
                return ResourceManager.GetString("Btn_NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Tavern.
        /// </summary>
        public static string Btn_ReturnToTavern {
            get {
                return ResourceManager.GetString("Btn_ReturnToTavern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        public static string Btn_Roll {
            get {
                return ResourceManager.GetString("Btn_Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Btn_StepBack {
            get {
                return ResourceManager.GetString("Btn_StepBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Sheet.
        /// </summary>
        public static string Btn_ViewSheet {
            get {
                return ResourceManager.GetString("Btn_ViewSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Advancement.
        /// </summary>
        public static string Character_Advancement {
            get {
                return ResourceManager.GetString("Character_Advancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        public static string Charisma {
            get {
                return ResourceManager.GetString("Charisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Progression &amp; Level Features.
        /// </summary>
        public static string Class_Progression {
            get {
                return ResourceManager.GetString("Class_Progression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to classes.
        /// </summary>
        public static string ClassCodex_BackToList {
            get {
                return ResourceManager.GetString("ClassCodex_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading classes....
        /// </summary>
        public static string ClassCodex_Loading {
            get {
                return ResourceManager.GetString("ClassCodex_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial and arcane archetypes with Hit Die indicators.
        /// </summary>
        public static string Classes_CardDescription {
            get {
                return ResourceManager.GetString("Classes_CardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes Catalog.
        /// </summary>
        public static string Classes_Catalog {
            get {
                return ResourceManager.GetString("Classes_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes &amp; Subclasses.
        /// </summary>
        public static string Classes_Subclasses {
            get {
                return ResourceManager.GetString("Classes_Subclasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        public static string Constitution {
            get {
                return ResourceManager.GetString("Constitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deception.
        /// </summary>
        public static string Deception {
            get {
                return ResourceManager.GetString("Deception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your hero has reached a training milestone. Choose a feat or increase scores..
        /// </summary>
        public static string Desc_FeatOrAsiSelection {
            get {
                return ResourceManager.GetString("Desc_FeatOrAsiSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe and balanced method recommended by rules.
        /// </summary>
        public static string Desc_FixedAverage {
            get {
                return ResourceManager.GetString("Desc_FixedAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how you want to forge your new physical endurance.
        /// </summary>
        public static string Desc_HitPointsGain {
            get {
                return ResourceManager.GetString("Desc_HitPointsGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave your fate to the dice.
        /// </summary>
        public static string Desc_RollDice {
            get {
                return ResourceManager.GetString("Desc_RollDice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        public static string Dexterity {
            get {
                return ResourceManager.GetString("Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon.
        /// </summary>
        public static string Dragon {
            get {
                return ResourceManager.GetString("Dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to feats.
        /// </summary>
        public static string FeatCodex_BackToList {
            get {
                return ResourceManager.GetString("FeatCodex_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading feats....
        /// </summary>
        public static string FeatCodex_Loading {
            get {
                return ResourceManager.GetString("FeatCodex_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feats.
        /// </summary>
        public static string Feats_Label {
            get {
                return ResourceManager.GetString("Feats_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feats.
        /// </summary>
        public static string Feats_Lib {
            get {
                return ResourceManager.GetString("Feats_Lib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore special feats and talents to customize your character..
        /// </summary>
        public static string Feats_Lib_Description {
            get {
                return ResourceManager.GetString("Feats_Lib_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Compendium.
        /// </summary>
        public static string Feature_Compendium {
            get {
                return ResourceManager.GetString("Feature_Compendium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fey.
        /// </summary>
        public static string Fey {
            get {
                return ResourceManager.GetString("Fey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Score.
        /// </summary>
        public static string Final_Score {
            get {
                return ResourceManager.GetString("Final_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it.
        /// </summary>
        public static string Got_it {
            get {
                return ResourceManager.GetString("Got_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humanoid.
        /// </summary>
        public static string Humanoid {
            get {
                return ResourceManager.GetString("Humanoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insight.
        /// </summary>
        public static string Insight {
            get {
                return ResourceManager.GetString("Insight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        public static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intimidation.
        /// </summary>
        public static string Intimidation {
            get {
                return ResourceManager.GetString("Intimidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation.
        /// </summary>
        public static string Investigation {
            get {
                return ResourceManager.GetString("Investigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability Scores.
        /// </summary>
        public static string Label_Attributes {
            get {
                return ResourceManager.GetString("Label_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casting Time.
        /// </summary>
        public static string Label_CastingTime {
            get {
                return ResourceManager.GetString("Label_CastingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Level.
        /// </summary>
        public static string Label_CurrentLevel {
            get {
                return ResourceManager.GetString("Label_CurrentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Granted.
        /// </summary>
        public static string Label_GrantSpell {
            get {
                return ResourceManager.GetString("Label_GrantSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Die.
        /// </summary>
        public static string Label_HitDie {
            get {
                return ResourceManager.GetString("Label_HitDie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Label_Languages {
            get {
                return ResourceManager.GetString("Label_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lvl.
        /// </summary>
        public static string Label_LevelShort {
            get {
                return ResourceManager.GetString("Label_LevelShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Level.
        /// </summary>
        public static string Label_NextLevel {
            get {
                return ResourceManager.GetString("Label_NextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Ability.
        /// </summary>
        public static string Label_PrimaryStat {
            get {
                return ResourceManager.GetString("Label_PrimaryStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFICIENCY BONUS.
        /// </summary>
        public static string Label_ProficiencyBonus {
            get {
                return ResourceManager.GetString("Label_ProficiencyBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Progression.
        /// </summary>
        public static string Label_Progression {
            get {
                return ResourceManager.GetString("Label_Progression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string Label_Range {
            get {
                return ResourceManager.GetString("Label_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Label_Size {
            get {
                return ResourceManager.GetString("Label_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Label_SlotLevel {
            get {
                return ResourceManager.GetString("Label_SlotLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Label_Speed {
            get {
                return ResourceManager.GetString("Label_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave empty (Grants +2 to first).
        /// </summary>
        public static string Leave_Empty_For_PlusTwo {
            get {
                return ResourceManager.GetString("Leave_Empty_For_PlusTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulting the grimoire....
        /// </summary>
        public static string Library_LoadingCounts {
            get {
                return ResourceManager.GetString("Library_LoadingCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineages &amp; Ancestries.
        /// </summary>
        public static string LineagesAndAncestries {
            get {
                return ResourceManager.GetString("LineagesAndAncestries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine.
        /// </summary>
        public static string Medicine {
            get {
                return ResourceManager.GetString("Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monstrosity.
        /// </summary>
        public static string Monstrosity {
            get {
                return ResourceManager.GetString("Monstrosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulting tavern records....
        /// </summary>
        public static string Msg_CheckingTavernLogs {
            get {
                return ResourceManager.GetString("Msg_CheckingTavernLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The adventure journal is empty still....
        /// </summary>
        public static string Msg_EmptyAdventureJournal {
            get {
                return ResourceManager.GetString("Msg_EmptyAdventureJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody has arrived at the inn yet. Go to the forge to create or import heroes!.
        /// </summary>
        public static string Msg_EmptyTavernHelp {
            get {
                return ResourceManager.GetString("Msg_EmptyTavernHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading progression scrolls....
        /// </summary>
        public static string Msg_LoadingProgression {
            get {
                return ResourceManager.GetString("Msg_LoadingProgression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The codex holds no origin stories yet. Import a content pack to reveal them..
        /// </summary>
        public static string Msg_NoBackgroundsFound {
            get {
                return ResourceManager.GetString("Msg_NoBackgroundsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The codex holds no class manuscripts yet. Import a content pack to reveal them..
        /// </summary>
        public static string Msg_NoClassesFound {
            get {
                return ResourceManager.GetString("Msg_NoClassesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no feats available to choose. Import a content pack to reveal them..
        /// </summary>
        public static string Msg_NoFeatsFound {
            get {
                return ResourceManager.GetString("Msg_NoFeatsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The codex holds no lineage records yet. Import a content pack to reveal them..
        /// </summary>
        public static string Msg_NoRacesFound {
            get {
                return ResourceManager.GetString("Msg_NoRacesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} pending feat(s) or ASI to choose..
        /// </summary>
        public static string Msg_PendingFeats {
            get {
                return ResourceManager.GetString("Msg_PendingFeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} pending spell(s) to learn..
        /// </summary>
        public static string Msg_PendingSpells {
            get {
                return ResourceManager.GetString("Msg_PendingSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per level.
        /// </summary>
        public static string Msg_PerLevel {
            get {
                return ResourceManager.GetString("Msg_PerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summoning hero from the astral plane....
        /// </summary>
        public static string Msg_SummoningHero {
            get {
                return ResourceManager.GetString("Msg_SummoningHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature.
        /// </summary>
        public static string Nature {
            get {
                return ResourceManager.GetString("Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Fixed Average.
        /// </summary>
        public static string Option_FixedAverage {
            get {
                return ResourceManager.GetString("Option_FixedAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Hit Dice.
        /// </summary>
        public static string Option_RollDice {
            get {
                return ResourceManager.GetString("Option_RollDice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perception.
        /// </summary>
        public static string Perception {
            get {
                return ResourceManager.GetString("Perception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persuasion.
        /// </summary>
        public static string Persuasion {
            get {
                return ResourceManager.GetString("Persuasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Stat focus archetype.
        /// </summary>
        public static string Primary_Stat {
            get {
                return ResourceManager.GetString("Primary_Stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progression with {0} active.
        /// </summary>
        public static string Progression_With_Subclass_Active {
            get {
                return ResourceManager.GetString("Progression_With_Subclass_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancestries, traits, and their subrace branches.
        /// </summary>
        public static string Race_Description {
            get {
                return ResourceManager.GetString("Race_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races &amp; Subraces.
        /// </summary>
        public static string Race_Subrace_Title {
            get {
                return ResourceManager.GetString("Race_Subrace_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to races.
        /// </summary>
        public static string RaceCodex_BackToList {
            get {
                return ResourceManager.GetString("RaceCodex_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading races....
        /// </summary>
        public static string RaceCodex_Loading {
            get {
                return ResourceManager.GetString("RaceCodex_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Manuscript from:.
        /// </summary>
        public static string Reading_Manuscript {
            get {
                return ResourceManager.GetString("Reading_Manuscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Directory.
        /// </summary>
        public static string Return_DirectoryBtn {
            get {
                return ResourceManager.GetString("Return_DirectoryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Attribute.
        /// </summary>
        public static string Select_Stat {
            get {
                return ResourceManager.GetString("Select_Stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Detail.
        /// </summary>
        public static string Skill_Detail {
            get {
                return ResourceManager.GetString("Skill_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleight of Hand.
        /// </summary>
        public static string SleightOfHand {
            get {
                return ResourceManager.GetString("SleightOfHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Notes.
        /// </summary>
        public static string Special_Notes {
            get {
                return ResourceManager.GetString("Special_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading spells....
        /// </summary>
        public static string SpellCodex_Loading {
            get {
                return ResourceManager.GetString("SpellCodex_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells &amp; Magic.
        /// </summary>
        public static string Spells_Magic {
            get {
                return ResourceManager.GetString("Spells_Magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by level, slots, and school of magic.
        /// </summary>
        public static string Spells_Magic_Description {
            get {
                return ResourceManager.GetString("Spells_Magic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign scores of 15, 14, 13, 12, 10, 8 strategically. You cannot repeat any value..
        /// </summary>
        public static string StandardArray_Instructions {
            get {
                return ResourceManager.GetString("StandardArray_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        public static string Stat_Cha {
            get {
                return ResourceManager.GetString("Stat_Cha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        public static string Stat_Con {
            get {
                return ResourceManager.GetString("Stat_Con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Stat_Str {
            get {
                return ResourceManager.GetString("Stat_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stealth.
        /// </summary>
        public static string Stealth {
            get {
                return ResourceManager.GetString("Stealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subclasses &amp; Archetypes.
        /// </summary>
        public static string Subclasses_Archetypes {
            get {
                return ResourceManager.GetString("Subclasses_Archetypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival.
        /// </summary>
        public static string Survival {
            get {
                return ResourceManager.GetString("Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feats &amp; ASI.
        /// </summary>
        public static string Tab_Feats_ASI {
            get {
                return ResourceManager.GetString("Tab_Feats_ASI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells.
        /// </summary>
        public static string Tab_Spells {
            get {
                return ResourceManager.GetString("Tab_Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitals.
        /// </summary>
        public static string Tab_Vitals {
            get {
                return ResourceManager.GetString("Tab_Vitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Table_Level {
            get {
                return ResourceManager.GetString("Table_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proficiency Bonus.
        /// </summary>
        public static string Table_ProficiencyBonus {
            get {
                return ResourceManager.GetString("Table_ProficiencyBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP Required.
        /// </summary>
        public static string Table_XpRequired {
            get {
                return ResourceManager.GetString("Table_XpRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Magic Energy.
        /// </summary>
        public static string Tip_AvailableSlot {
            get {
                return ResourceManager.GetString("Tip_AvailableSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expended Slot (Requires Long Rest).
        /// </summary>
        public static string Tip_ExpendedSlot {
            get {
                return ResourceManager.GetString("Tip_ExpendedSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &amp; Race Features.
        /// </summary>
        public static string Title_ClassAndRaceFeatures {
            get {
                return ResourceManager.GetString("Title_ClassAndRaceFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse the complete game catalog. Tap any index card to expand its..
        /// </summary>
        public static string Title_Description {
            get {
                return ResourceManager.GetString("Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feats &amp; Attribute Injections.
        /// </summary>
        public static string Title_FeatOrAsiSelection {
            get {
                return ResourceManager.GetString("Title_FeatOrAsiSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Points Gain.
        /// </summary>
        public static string Title_HitPointsGain {
            get {
                return ResourceManager.GetString("Title_HitPointsGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Up.
        /// </summary>
        public static string Title_LevelUp {
            get {
                return ResourceManager.GetString("Title_LevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Adventurers.
        /// </summary>
        public static string Title_MyAdventurers {
            get {
                return ResourceManager.GetString("Title_MyAdventurers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Game Codex.
        /// </summary>
        public static string Title_Name {
            get {
                return ResourceManager.GetString("Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backgrounds found.
        /// </summary>
        public static string Title_NoBackgroundsFound {
            get {
                return ResourceManager.GetString("Title_NoBackgroundsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No classes found.
        /// </summary>
        public static string Title_NoClassesFound {
            get {
                return ResourceManager.GetString("Title_NoClassesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No feats found.
        /// </summary>
        public static string Title_NoFeatsFound {
            get {
                return ResourceManager.GetString("Title_NoFeatsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No races found.
        /// </summary>
        public static string Title_NoRacesFound {
            get {
                return ResourceManager.GetString("Title_NoRacesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Selections.
        /// </summary>
        public static string Title_PendingSelections {
            get {
                return ResourceManager.GetString("Title_PendingSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your Path.
        /// </summary>
        public static string Title_SelectClass {
            get {
                return ResourceManager.GetString("Title_SelectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Title_Skills {
            get {
                return ResourceManager.GetString("Title_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellbook.
        /// </summary>
        public static string Title_Spellbook {
            get {
                return ResourceManager.GetString("Title_Spellbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells Learning.
        /// </summary>
        public static string Title_SpellsLearning {
            get {
                return ResourceManager.GetString("Title_SpellsLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Slots.
        /// </summary>
        public static string Title_SpellSlots {
            get {
                return ResourceManager.GetString("Title_SpellSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcane Points.
        /// </summary>
        public static string TraitType_ArcanePoints {
            get {
                return ResourceManager.GetString("TraitType_ArcanePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beast Form.
        /// </summary>
        public static string TraitType_BeastFormCount {
            get {
                return ResourceManager.GetString("TraitType_BeastFormCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonded Magic Slots.
        /// </summary>
        public static string TraitType_BondedSlots {
            get {
                return ResourceManager.GetString("TraitType_BondedSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantrips Known.
        /// </summary>
        public static string TraitType_CantripsKnown {
            get {
                return ResourceManager.GetString("TraitType_CantripsKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen Enemy.
        /// </summary>
        public static string TraitType_ChosenEnemyUses {
            get {
                return ResourceManager.GetString("TraitType_ChosenEnemyUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Points.
        /// </summary>
        public static string TraitType_FocusPoints {
            get {
                return ResourceManager.GetString("TraitType_FocusPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frenzy.
        /// </summary>
        public static string TraitType_FrenzyCount {
            get {
                return ResourceManager.GetString("TraitType_FrenzyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frenzy Damage.
        /// </summary>
        public static string TraitType_FrenzyDamage {
            get {
                return ResourceManager.GetString("TraitType_FrenzyDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspiration Die.
        /// </summary>
        public static string TraitType_InspirationDie {
            get {
                return ResourceManager.GetString("TraitType_InspirationDie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcane Invocations.
        /// </summary>
        public static string TraitType_InvocationsKnown {
            get {
                return ResourceManager.GetString("TraitType_InvocationsKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision Attack Die.
        /// </summary>
        public static string TraitType_PrecisionAttackDie {
            get {
                return ResourceManager.GetString("TraitType_PrecisionAttackDie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared Spells.
        /// </summary>
        public static string TraitType_PreparedSpellsCount {
            get {
                return ResourceManager.GetString("TraitType_PreparedSpellsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacred Power.
        /// </summary>
        public static string TraitType_Sacred_PowerUses {
            get {
                return ResourceManager.GetString("TraitType_Sacred PowerUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacred Power.
        /// </summary>
        public static string TraitType_SacredPowerCount {
            get {
                return ResourceManager.GetString("TraitType_SacredPowerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Breath.
        /// </summary>
        public static string TraitType_SecondBreathUses {
            get {
                return ResourceManager.GetString("TraitType_SecondBreathUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Level.
        /// </summary>
        public static string TraitType_SlotLevel {
            get {
                return ResourceManager.GetString("TraitType_SlotLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Slots.
        /// </summary>
        public static string TraitType_SpellSlots {
            get {
                return ResourceManager.GetString("TraitType_SpellSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unarmed Strike Die.
        /// </summary>
        public static string TraitType_UnarmedStrikeDie {
            get {
                return ResourceManager.GetString("TraitType_UnarmedStrikeDie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unarmored Movement.
        /// </summary>
        public static string TraitType_UnarmoredMovement {
            get {
                return ResourceManager.GetString("TraitType_UnarmoredMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Expertise.
        /// </summary>
        public static string TraitType_WeaponExpertiseCount {
            get {
                return ResourceManager.GetString("TraitType_WeaponExpertiseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Select Archetype.
        /// </summary>
        public static string Un_Select_Archetype {
            get {
                return ResourceManager.GetString("Un_Select_Archetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undead.
        /// </summary>
        public static string Undead {
            get {
                return ResourceManager.GetString("Undead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft..
        /// </summary>
        public static string Unit_Feet {
            get {
                return ResourceManager.GetString("Unit_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom.
        /// </summary>
        public static string Wisdom {
            get {
                return ResourceManager.GetString("Wisdom", resourceCulture);
            }
        }
    }
}
