<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RafeTale.Application\RafeTale.Application.csproj" />
    <ProjectReference Include="..\RafeTale.Domain\RafeTale.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Character\" />
    <Folder Include="Components\UI\" />
  </ItemGroup>

</Project>
