//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDreams.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnDreams.Application.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Tavern.
        /// </summary>
        public static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understood.
        /// </summary>
        public static string Btn_Confirm {
            get {
                return ResourceManager.GetString("Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Path.
        /// </summary>
        public static string Btn_ConfirmClass {
            get {
                return ResourceManager.GetString("Btn_ConfirmClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Lineage.
        /// </summary>
        public static string Btn_ConfirmRace {
            get {
                return ResourceManager.GetString("Btn_ConfirmRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge Character.
        /// </summary>
        public static string Btn_CreateHero {
            get {
                return ResourceManager.GetString("Btn_CreateHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a path....
        /// </summary>
        public static string Choose_Class {
            get {
                return ResourceManager.GetString("Choose_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Race.
        /// </summary>
        public static string Choose_Race {
            get {
                return ResourceManager.GetString("Choose_Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casting Time.
        /// </summary>
        public static string Label_CastingTime {
            get {
                return ResourceManager.GetString("Label_CastingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class / Path.
        /// </summary>
        public static string Label_Class {
            get {
                return ResourceManager.GetString("Label_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Granted.
        /// </summary>
        public static string Label_GrantSpell {
            get {
                return ResourceManager.GetString("Label_GrantSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Name.
        /// </summary>
        public static string Label_HeroName {
            get {
                return ResourceManager.GetString("Label_HeroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Story.
        /// </summary>
        public static string Label_History {
            get {
                return ResourceManager.GetString("Label_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Die.
        /// </summary>
        public static string Label_HitDie {
            get {
                return ResourceManager.GetString("Label_HitDie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Label_Languages {
            get {
                return ResourceManager.GetString("Label_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lvl.
        /// </summary>
        public static string Label_LevelShort {
            get {
                return ResourceManager.GetString("Label_LevelShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Ability.
        /// </summary>
        public static string Label_PrimaryStat {
            get {
                return ResourceManager.GetString("Label_PrimaryStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Progression.
        /// </summary>
        public static string Label_Progression {
            get {
                return ResourceManager.GetString("Label_Progression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race / Lineage.
        /// </summary>
        public static string Label_Race {
            get {
                return ResourceManager.GetString("Label_Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability Score Increase.
        /// </summary>
        public static string Label_RaceAbilities {
            get {
                return ResourceManager.GetString("Label_RaceAbilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string Label_Range {
            get {
                return ResourceManager.GetString("Label_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Details.
        /// </summary>
        public static string Label_SelectionDetails {
            get {
                return ResourceManager.GetString("Label_SelectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Label_Size {
            get {
                return ResourceManager.GetString("Label_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Label_Speed {
            get {
                return ResourceManager.GetString("Label_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Label_Strength {
            get {
                return ResourceManager.GetString("Label_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racial Traits.
        /// </summary>
        public static string Label_Traits {
            get {
                return ResourceManager.GetString("Label_Traits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your lineage and path to see their secrets....
        /// </summary>
        public static string Msg_EmptySelection {
            get {
                return ResourceManager.GetString("Msg_EmptySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per level.
        /// </summary>
        public static string Msg_PerLevel {
            get {
                return ResourceManager.GetString("Msg_PerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore the lineages of the world....
        /// </summary>
        public static string Msg_SelectRacePrompt {
            get {
                return ResourceManager.GetString("Msg_SelectRacePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the legend of your hero here....
        /// </summary>
        public static string Placeholder_History {
            get {
                return ResourceManager.GetString("Placeholder_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Alistair Ironfoot....
        /// </summary>
        public static string Placeholder_Name {
            get {
                return ResourceManager.GetString("Placeholder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        public static string Stat_Cha {
            get {
                return ResourceManager.GetString("Stat_Cha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        public static string Stat_Con {
            get {
                return ResourceManager.GetString("Stat_Con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Stat_Str {
            get {
                return ResourceManager.GetString("Stat_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your legend begins with a single decision....
        /// </summary>
        public static string Subtitle_Creation {
            get {
                return ResourceManager.GetString("Subtitle_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Hero.
        /// </summary>
        public static string Title_NewHero {
            get {
                return ResourceManager.GetString("Title_NewHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your Path.
        /// </summary>
        public static string Title_SelectClass {
            get {
                return ResourceManager.GetString("Title_SelectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your Lineage.
        /// </summary>
        public static string Title_SelectRace {
            get {
                return ResourceManager.GetString("Title_SelectRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Identity.
        /// </summary>
        public static string Title_StepIdentity {
            get {
                return ResourceManager.GetString("Title_StepIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft..
        /// </summary>
        public static string Unit_Feet {
            get {
                return ResourceManager.GetString("Unit_Feet", resourceCulture);
            }
        }
    }
}
