//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDreams.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibraryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibraryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnDreams.Application.Resources.LibraryStrings", typeof(LibraryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Library.
        /// </summary>
        public static string Back_LibraryBtn {
            get {
                return ResourceManager.GetString("Back_LibraryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Progression &amp; Level Features.
        /// </summary>
        public static string Class_Progression {
            get {
                return ResourceManager.GetString("Class_Progression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial and arcane archetypes with Hit Die indicators..
        /// </summary>
        public static string Classes_CardDescription {
            get {
                return ResourceManager.GetString("Classes_CardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes Catalog.
        /// </summary>
        public static string Classes_Catalog {
            get {
                return ResourceManager.GetString("Classes_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes &amp; Subclasses.
        /// </summary>
        public static string Classes_Subclasses {
            get {
                return ResourceManager.GetString("Classes_Subclasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon.
        /// </summary>
        public static string Dragon {
            get {
                return ResourceManager.GetString("Dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Compendium.
        /// </summary>
        public static string Feature_Compendium {
            get {
                return ResourceManager.GetString("Feature_Compendium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fey.
        /// </summary>
        public static string Fey {
            get {
                return ResourceManager.GetString("Fey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it.
        /// </summary>
        public static string Got_it {
            get {
                return ResourceManager.GetString("Got_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humanoid.
        /// </summary>
        public static string Humanoid {
            get {
                return ResourceManager.GetString("Humanoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineages &amp; Ancestries.
        /// </summary>
        public static string LineagesAndAncestries {
            get {
                return ResourceManager.GetString("LineagesAndAncestries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monstrosity.
        /// </summary>
        public static string Monstrosity {
            get {
                return ResourceManager.GetString("Monstrosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Stat focus archetype.
        /// </summary>
        public static string Primary_Stat {
            get {
                return ResourceManager.GetString("Primary_Stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progression with {0} active.
        /// </summary>
        public static string Progression_With_Subclass_Active {
            get {
                return ResourceManager.GetString("Progression_With_Subclass_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancestries, traits, and their subrace branches..
        /// </summary>
        public static string Race_Description {
            get {
                return ResourceManager.GetString("Race_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races &amp; Subraces.
        /// </summary>
        public static string Race_Subrace_Title {
            get {
                return ResourceManager.GetString("Race_Subrace_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Manuscript from:.
        /// </summary>
        public static string Reading_Manuscript {
            get {
                return ResourceManager.GetString("Reading_Manuscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Directory.
        /// </summary>
        public static string Return_DirectoryBtn {
            get {
                return ResourceManager.GetString("Return_DirectoryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Notes.
        /// </summary>
        public static string Special_Notes {
            get {
                return ResourceManager.GetString("Special_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells &amp; Magic.
        /// </summary>
        public static string Spells_Magic {
            get {
                return ResourceManager.GetString("Spells_Magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by level, slots, and school of magic..
        /// </summary>
        public static string Spells_Magic_Description {
            get {
                return ResourceManager.GetString("Spells_Magic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subclasses &amp; Archetypes.
        /// </summary>
        public static string Subclasses_Archetypes {
            get {
                return ResourceManager.GetString("Subclasses_Archetypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse the complete D&amp;D 2024 catalog. Tap any index card to expand its.
        /// </summary>
        public static string Title_Description {
            get {
                return ResourceManager.GetString("Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Game Codex.
        /// </summary>
        public static string Title_Name {
            get {
                return ResourceManager.GetString("Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Select Archetype.
        /// </summary>
        public static string Un_Select_Archetype {
            get {
                return ResourceManager.GetString("Un_Select_Archetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undead.
        /// </summary>
        public static string Undead {
            get {
                return ResourceManager.GetString("Undead", resourceCulture);
            }
        }
    }
}
