// <auto-generated />
using System;
using DnDreams.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnDreams.Infrastructure.Migrations
{
    [DbContext(typeof(DnDreamsDbContext))]
    partial class DnDreamsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("CharacterFeat", b =>
                {
                    b.Property<Guid>("AcquiredFeatsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.HasKey("AcquiredFeatsId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterFeat");
                });

            modelBuilder.Entity("CharacterFeature", b =>
                {
                    b.Property<Guid>("AcquiredFeaturesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.HasKey("AcquiredFeaturesId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterFeature");
                });

            modelBuilder.Entity("CharacterSpell", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KnownSpellsId")
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId", "KnownSpellsId");

                    b.HasIndex("KnownSpellsId");

                    b.ToTable("CharacterSpell");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.ActiveModifiers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DurationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RemainingRounds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetProperty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("ActiveModifiers", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DungeonMasterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.CampaignCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CampaignCharacters", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClassDefId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stats")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassDefId");

                    b.HasIndex("RaceId");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.CharacterInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemTemplateId");

                    b.ToTable("CharacterInventories", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.CharacterModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterModifiers", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.CharacterSpellSlots", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsedSlots")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterSpellSlots", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.CharacterStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveConditions")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeathSaveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeathSaveSuccesses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemporaryHp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterStatus", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.ClassDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmorProficiencies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HitDie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryAbility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SavingThrowProficiencies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillProficiencies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillsToChoose")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SpellId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponProficiencies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpellId");

                    b.ToTable("ClassDefinitions", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.ClassLevelProgression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClassDefId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ClassDefId");

                    b.ToTable("ClassLevelProgressions");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Feat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prerequisite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Feats");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClassLevelProgressionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresChoice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassLevelProgressionId");

                    b.ToTable("Features", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.ItemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DamageDice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GoldValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("ItemTemplates");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CharacterId");

                    b.ToTable("JournalEntries", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.LocalizedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Property", "LanguageCode")
                        .IsUnique();

                    b.ToTable("LocalizedContents", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatureType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Darkvision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RacialTraits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Speed")
                        .HasColumnType("REAL");

                    b.Property<string>("StatBonuses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicalName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Races", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Concentration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ritual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Spells", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.SubRace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("SubRaces", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Trait", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("Traits", (string)null);
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.XpRules", b =>
                {
                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bonus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredXp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Level");

                    b.ToTable("XpRules", (string)null);
                });

            modelBuilder.Entity("LanguageRace", b =>
                {
                    b.Property<Guid>("LanguagesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RacesId")
                        .HasColumnType("TEXT");

                    b.HasKey("LanguagesId", "RacesId");

                    b.HasIndex("RacesId");

                    b.ToTable("LanguageRace");
                });

            modelBuilder.Entity("CharacterFeat", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Feat", null)
                        .WithMany()
                        .HasForeignKey("AcquiredFeatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDreams.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterFeature", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Feature", null)
                        .WithMany()
                        .HasForeignKey("AcquiredFeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDreams.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterSpell", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDreams.Domain.Entities.Spell", null)
                        .WithMany()
                        .HasForeignKey("KnownSpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.ActiveModifiers", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Character", "Character")
                        .WithMany("ActiveModifiers")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.CampaignCharacter", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Campaign", "Campaign")
                        .WithMany("CampaignCharacters")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDreams.Domain.Entities.Character", "Character")
                        .WithMany("CampaignCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Character", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.ClassDefinition", "ClassDef")
                        .WithMany()
                        .HasForeignKey("ClassDefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDreams.Domain.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassDef");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.CharacterInventory", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Character", null)
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDreams.Domain.Entities.ItemTemplate", "Item")
                        .WithMany()
                        .HasForeignKey("ItemTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.CharacterModifier", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Character", null)
                        .WithMany("CharacterModifiers")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.CharacterSpellSlots", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Character", "Character")
                        .WithMany("SpellSlots")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.CharacterStatus", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Character", "Character")
                        .WithOne("Status")
                        .HasForeignKey("DnDreams.Domain.Entities.CharacterStatus", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.ClassDefinition", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Spell", null)
                        .WithMany("Classes")
                        .HasForeignKey("SpellId");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.ClassLevelProgression", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Character", null)
                        .WithMany("ClassLevels")
                        .HasForeignKey("CharacterId");

                    b.HasOne("DnDreams.Domain.Entities.ClassDefinition", "ClassDef")
                        .WithMany("Progressions")
                        .HasForeignKey("ClassDefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassDef");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Feature", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.ClassLevelProgression", null)
                        .WithMany("Features")
                        .HasForeignKey("ClassLevelProgressionId");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.JournalEntry", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DnDreams.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Campaign");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.SubRace", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Race", "Race")
                        .WithMany("SubRaces")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Trait", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Race", "Race")
                        .WithMany("Traits")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("LanguageRace", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDreams.Domain.Entities.Race", null)
                        .WithMany()
                        .HasForeignKey("RacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("CampaignCharacters");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Character", b =>
                {
                    b.Navigation("ActiveModifiers");

                    b.Navigation("CampaignCharacters");

                    b.Navigation("CharacterModifiers");

                    b.Navigation("ClassLevels");

                    b.Navigation("Inventory");

                    b.Navigation("SpellSlots");

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.ClassDefinition", b =>
                {
                    b.Navigation("Progressions");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.ClassLevelProgression", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Race", b =>
                {
                    b.Navigation("SubRaces");

                    b.Navigation("Traits");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Spell", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
