// <auto-generated />
using System;
using DnDreams.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnDreams.Infrastructure.Migrations
{
    [DbContext(typeof(DnDreamsDbContext))]
    partial class DnDreamsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("DnDreams.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClassDefId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stats")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassDefId");

                    b.HasIndex("RaceId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.ClassDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("HitDie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClassDefinitions");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.ClassLevelProgression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClassDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ClassDefinitionId");

                    b.ToTable("ClassLevelProgression");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatBonuses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("DnDreams.Domain.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClassLevelProgressionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresChoice")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ClassLevelProgressionId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Character", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.ClassDefinition", "ClassDef")
                        .WithMany()
                        .HasForeignKey("ClassDefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDreams.Domain.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassDef");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.ClassLevelProgression", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Character", null)
                        .WithMany("ClassLevels")
                        .HasForeignKey("CharacterId");

                    b.HasOne("DnDreams.Domain.Entities.ClassDefinition", null)
                        .WithMany("Progression")
                        .HasForeignKey("ClassDefinitionId");
                });

            modelBuilder.Entity("DnDreams.Domain.Feature", b =>
                {
                    b.HasOne("DnDreams.Domain.Entities.Character", null)
                        .WithMany("AcquiredFeatures")
                        .HasForeignKey("CharacterId");

                    b.HasOne("DnDreams.Domain.Entities.ClassLevelProgression", null)
                        .WithMany("Features")
                        .HasForeignKey("ClassLevelProgressionId");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.Character", b =>
                {
                    b.Navigation("AcquiredFeatures");

                    b.Navigation("ClassLevels");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.ClassDefinition", b =>
                {
                    b.Navigation("Progression");
                });

            modelBuilder.Entity("DnDreams.Domain.Entities.ClassLevelProgression", b =>
                {
                    b.Navigation("Features");
                });
#pragma warning restore 612, 618
        }
    }
}
