//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rafedream.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rafedream.Application.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  BonusAction.
        /// </summary>
        public static string _SpellCastTime_BonusAction {
            get {
                return ResourceManager.GetString(" SpellCastTime_BonusAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hour.
        /// </summary>
        public static string _SpellCastTime_Hour {
            get {
                return ResourceManager.GetString(" SpellCastTime_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Minute.
        /// </summary>
        public static string _SpellCastTime_Minute {
            get {
                return ResourceManager.GetString(" SpellCastTime_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Reaction.
        /// </summary>
        public static string _SpellCastTime_Reaction {
            get {
                return ResourceManager.GetString(" SpellCastTime_Reaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Special.
        /// </summary>
        public static string _SpellCastTime_Special {
            get {
                return ResourceManager.GetString(" SpellCastTime_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abilities allocation.
        /// </summary>
        public static string Abilities_Title {
            get {
                return ResourceManager.GetString("Abilities_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrobatics.
        /// </summary>
        public static string Acrobatics {
            get {
                return ResourceManager.GetString("Acrobatics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Handling.
        /// </summary>
        public static string Animal_Handling {
            get {
                return ResourceManager.GetString("Animal Handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rafedream.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your own legend.
        /// </summary>
        public static string AppSlogan {
            get {
                return ResourceManager.GetString("AppSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcana.
        /// </summary>
        public static string Arcana {
            get {
                return ResourceManager.GetString("Arcana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Training.
        /// </summary>
        public static string Armor_Proficiencies {
            get {
                return ResourceManager.GetString("Armor_Proficiencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athletics.
        /// </summary>
        public static string Athletics {
            get {
                return ResourceManager.GetString("Athletics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atributos (ASI).
        /// </summary>
        public static string Background_AbilityScores {
            get {
                return ResourceManager.GetString("Background_AbilityScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Puedes aplicar un aumento de +2 a uno de estos atributos y +1 a otro, o un +1 a los tres..
        /// </summary>
        public static string Background_ASINote {
            get {
                return ResourceManager.GetString("Background_ASINote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background attribute bonus.
        /// </summary>
        public static string Background_Bonus {
            get {
                return ResourceManager.GetString("Background_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backgrounds.
        /// </summary>
        public static string Background_Catalog {
            get {
                return ResourceManager.GetString("Background_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dote de Origen (Nivel 1).
        /// </summary>
        public static string Background_OriginFeat {
            get {
                return ResourceManager.GetString("Background_OriginFeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dote de Origen.
        /// </summary>
        public static string Background_OriginFeatBadge {
            get {
                return ResourceManager.GetString("Background_OriginFeatBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competencias en Habilidades.
        /// </summary>
        public static string Background_SkillProficiencies {
            get {
                return ResourceManager.GetString("Background_SkillProficiencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo Inicial.
        /// </summary>
        public static string Background_StartingEquipment {
            get {
                return ResourceManager.GetString("Background_StartingEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competencias en Herramientas.
        /// </summary>
        public static string Background_ToolProficiencies {
            get {
                return ResourceManager.GetString("Background_ToolProficiencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast.
        /// </summary>
        public static string Btn_Cast {
            get {
                return ResourceManager.GetString("Btn_Cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a feat.
        /// </summary>
        public static string Btn_ChooseFeat {
            get {
                return ResourceManager.GetString("Btn_ChooseFeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim selections.
        /// </summary>
        public static string Btn_ClaimSelections {
            get {
                return ResourceManager.GetString("Btn_ClaimSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear History.
        /// </summary>
        public static string Btn_ClearHistory {
            get {
                return ResourceManager.GetString("Btn_ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understood.
        /// </summary>
        public static string Btn_Confirm {
            get {
                return ResourceManager.GetString("Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Path.
        /// </summary>
        public static string Btn_ConfirmClass {
            get {
                return ResourceManager.GetString("Btn_ConfirmClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm level up completion.
        /// </summary>
        public static string Btn_ConfirmLevelUp {
            get {
                return ResourceManager.GetString("Btn_ConfirmLevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Lineage.
        /// </summary>
        public static string Btn_ConfirmRace {
            get {
                return ResourceManager.GetString("Btn_ConfirmRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge Character.
        /// </summary>
        public static string Btn_CreateHero {
            get {
                return ResourceManager.GetString("Btn_CreateHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish character creation.
        /// </summary>
        public static string Btn_FinishCharacter {
            get {
                return ResourceManager.GetString("Btn_FinishCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase stats (ASI).
        /// </summary>
        public static string Btn_IncreaseStats {
            get {
                return ResourceManager.GetString("Btn_IncreaseStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level up.
        /// </summary>
        public static string Btn_LevelUp {
            get {
                return ResourceManager.GetString("Btn_LevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Rest.
        /// </summary>
        public static string Btn_LongRest {
            get {
                return ResourceManager.GetString("Btn_LongRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to next step.
        /// </summary>
        public static string Btn_NextStep {
            get {
                return ResourceManager.GetString("Btn_NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to tavern.
        /// </summary>
        public static string Btn_ReturnToTavern {
            get {
                return ResourceManager.GetString("Btn_ReturnToTavern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll dice.
        /// </summary>
        public static string Btn_Roll {
            get {
                return ResourceManager.GetString("Btn_Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to previous step.
        /// </summary>
        public static string Btn_StepBack {
            get {
                return ResourceManager.GetString("Btn_StepBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Sheet.
        /// </summary>
        public static string Btn_ViewSheet {
            get {
                return ResourceManager.GetString("Btn_ViewSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CombatStyle.
        /// </summary>
        public static string CategoryFeat_CombatStyle {
            get {
                return ResourceManager.GetString("CategoryFeat_CombatStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EpicFeat.
        /// </summary>
        public static string CategoryFeat_EpicFeat {
            get {
                return ResourceManager.GetString("CategoryFeat_EpicFeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string CategoryFeat_General {
            get {
                return ResourceManager.GetString("CategoryFeat_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string CategoryFeat_Origin {
            get {
                return ResourceManager.GetString("CategoryFeat_Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma .
        /// </summary>
        public static string Charisma {
            get {
                return ResourceManager.GetString("Charisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a path....
        /// </summary>
        public static string Choose_Class {
            get {
                return ResourceManager.GetString("Choose_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Race.
        /// </summary>
        public static string Choose_Race {
            get {
                return ResourceManager.GetString("Choose_Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbarian.
        /// </summary>
        public static string Class_Barbarian {
            get {
                return ResourceManager.GetString("Class_Barbarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bard.
        /// </summary>
        public static string Class_Bard {
            get {
                return ResourceManager.GetString("Class_Bard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Basic Atributes.
        /// </summary>
        public static string Class_Basic_Atributes {
            get {
                return ResourceManager.GetString("Class_Basic_Atributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleric.
        /// </summary>
        public static string Class_Cleric {
            get {
                return ResourceManager.GetString("Class_Cleric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        public static string Class_Druid {
            get {
                return ResourceManager.GetString("Class_Druid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter.
        /// </summary>
        public static string Class_Fighter {
            get {
                return ResourceManager.GetString("Class_Fighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monk.
        /// </summary>
        public static string Class_Monk {
            get {
                return ResourceManager.GetString("Class_Monk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladin.
        /// </summary>
        public static string Class_Paladin {
            get {
                return ResourceManager.GetString("Class_Paladin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranger.
        /// </summary>
        public static string Class_Ranger {
            get {
                return ResourceManager.GetString("Class_Ranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        public static string Class_Rogue {
            get {
                return ResourceManager.GetString("Class_Rogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorcerer.
        /// </summary>
        public static string Class_Sorcerer {
            get {
                return ResourceManager.GetString("Class_Sorcerer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warlock.
        /// </summary>
        public static string Class_Warlock {
            get {
                return ResourceManager.GetString("Class_Warlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        public static string Class_Wizard {
            get {
                return ResourceManager.GetString("Class_Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninguna.
        /// </summary>
        public static string Common_None {
            get {
                return ResourceManager.GetString("Common_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution .
        /// </summary>
        public static string Constitution {
            get {
                return ResourceManager.GetString("Constitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deception.
        /// </summary>
        public static string Deception {
            get {
                return ResourceManager.GetString("Deception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feat or ASI options.
        /// </summary>
        public static string Desc_FeatOrAsiSelection {
            get {
                return ResourceManager.GetString("Desc_FeatOrAsiSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation of fixed average hit points value.
        /// </summary>
        public static string Desc_FixedAverage {
            get {
                return ResourceManager.GetString("Desc_FixedAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling or taking average hit points.
        /// </summary>
        public static string Desc_HitPointsGain {
            get {
                return ResourceManager.GetString("Desc_HitPointsGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit points dice rolling.
        /// </summary>
        public static string Desc_RollDice {
            get {
                return ResourceManager.GetString("Desc_RollDice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        public static string Dexterity {
            get {
                return ResourceManager.GetString("Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exotic.
        /// </summary>
        public static string Exotic {
            get {
                return ResourceManager.GetString("Exotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feats Catalog.
        /// </summary>
        public static string Feat_Catalog {
            get {
                return ResourceManager.GetString("Feat_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisite.
        /// </summary>
        public static string Feat_Prerequisite {
            get {
                return ResourceManager.GetString("Feat_Prerequisite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy.
        /// </summary>
        public static string Heavy {
            get {
                return ResourceManager.GetString("Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Point Die.
        /// </summary>
        public static string Hit_Die {
            get {
                return ResourceManager.GetString("Hit_Die", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insight.
        /// </summary>
        public static string Insight {
            get {
                return ResourceManager.GetString("Insight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence .
        /// </summary>
        public static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intimidation.
        /// </summary>
        public static string Intimidation {
            get {
                return ResourceManager.GetString("Intimidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation.
        /// </summary>
        public static string Investigation {
            get {
                return ResourceManager.GetString("Investigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Label_AboutItem {
            get {
                return ResourceManager.GetString("Label_AboutItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditing level.
        /// </summary>
        public static string Label_AuditingLevel {
            get {
                return ResourceManager.GetString("Label_AuditingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantrip.
        /// </summary>
        public static string Label_Cantrip {
            get {
                return ResourceManager.GetString("Label_Cantrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casting Time.
        /// </summary>
        public static string Label_CastingTime {
            get {
                return ResourceManager.GetString("Label_CastingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class / Path.
        /// </summary>
        public static string Label_Class {
            get {
                return ResourceManager.GetString("Label_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label indicating class spell availability.
        /// </summary>
        public static string Label_ClassSpellsAvailable {
            get {
                return ResourceManager.GetString("Label_ClassSpellsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creature Type.
        /// </summary>
        public static string Label_CreatureType {
            get {
                return ResourceManager.GetString("Label_CreatureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current level.
        /// </summary>
        public static string Label_CurrentLevel {
            get {
                return ResourceManager.GetString("Label_CurrentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Level.
        /// </summary>
        public static string Label_FilterLevel {
            get {
                return ResourceManager.GetString("Label_FilterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feet.
        /// </summary>
        public static string Label_ft {
            get {
                return ResourceManager.GetString("Label_ft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Granted.
        /// </summary>
        public static string Label_GrantSpell {
            get {
                return ResourceManager.GetString("Label_GrantSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Name.
        /// </summary>
        public static string Label_HeroName {
            get {
                return ResourceManager.GetString("Label_HeroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Story.
        /// </summary>
        public static string Label_History {
            get {
                return ResourceManager.GetString("Label_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Die.
        /// </summary>
        public static string Label_HitDie {
            get {
                return ResourceManager.GetString("Label_HitDie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Label_Languages {
            get {
                return ResourceManager.GetString("Label_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lvl.
        /// </summary>
        public static string Label_LevelShort {
            get {
                return ResourceManager.GetString("Label_LevelShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metters.
        /// </summary>
        public static string Label_mt {
            get {
                return ResourceManager.GetString("Label_mt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next level.
        /// </summary>
        public static string Label_NextLevel {
            get {
                return ResourceManager.GetString("Label_NextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Ability.
        /// </summary>
        public static string Label_PrimaryStat {
            get {
                return ResourceManager.GetString("Label_PrimaryStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof.
        /// </summary>
        public static string Label_Proficiency {
            get {
                return ResourceManager.GetString("Label_Proficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Progression.
        /// </summary>
        public static string Label_Progression {
            get {
                return ResourceManager.GetString("Label_Progression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race / Lineage.
        /// </summary>
        public static string Label_Race {
            get {
                return ResourceManager.GetString("Label_Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability Score Increase.
        /// </summary>
        public static string Label_RaceAbilities {
            get {
                return ResourceManager.GetString("Label_RaceAbilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string Label_Range {
            get {
                return ResourceManager.GetString("Label_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Rolls.
        /// </summary>
        public static string Label_RecentRolls {
            get {
                return ResourceManager.GetString("Label_RecentRolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Die.
        /// </summary>
        public static string Label_SelectDice {
            get {
                return ResourceManager.GetString("Label_SelectDice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Details.
        /// </summary>
        public static string Label_SelectionDetails {
            get {
                return ResourceManager.GetString("Label_SelectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Label_Size {
            get {
                return ResourceManager.GetString("Label_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Category.
        /// </summary>
        public static string Label_SizeCategory {
            get {
                return ResourceManager.GetString("Label_SizeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Label_SlotLevel {
            get {
                return ResourceManager.GetString("Label_SlotLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Label_Speed {
            get {
                return ResourceManager.GetString("Label_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Label_Strength {
            get {
                return ResourceManager.GetString("Label_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racial Traits.
        /// </summary>
        public static string Label_Traits {
            get {
                return ResourceManager.GetString("Label_Traits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        public static string Label_Velocity {
            get {
                return ResourceManager.GetString("Label_Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option to leave second stat empty for a +2 bonus.
        /// </summary>
        public static string Leave_Empty_For_PlusTwo {
            get {
                return ResourceManager.GetString("Leave_Empty_For_PlusTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial.
        /// </summary>
        public static string Martial {
            get {
                return ResourceManager.GetString("Martial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial Finesse.
        /// </summary>
        public static string MartialFinesse {
            get {
                return ResourceManager.GetString("MartialFinesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial Light.
        /// </summary>
        public static string MartialLight {
            get {
                return ResourceManager.GetString("MartialLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine.
        /// </summary>
        public static string Medicine {
            get {
                return ResourceManager.GetString("Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Table.
        /// </summary>
        public static string Modal_Table_Title {
            get {
                return ResourceManager.GetString("Modal_Table_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulting tavern records....
        /// </summary>
        public static string Msg_CheckingTavernLogs {
            get {
                return ResourceManager.GetString("Msg_CheckingTavernLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure journal / features list is empty.
        /// </summary>
        public static string Msg_EmptyAdventureJournal {
            get {
                return ResourceManager.GetString("Msg_EmptyAdventureJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your grimoire is empty..
        /// </summary>
        public static string Msg_EmptyGrimoire {
            get {
                return ResourceManager.GetString("Msg_EmptyGrimoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your lineage and path to see their secrets....
        /// </summary>
        public static string Msg_EmptySelection {
            get {
                return ResourceManager.GetString("Msg_EmptySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody has arrived at the inn yet. Go to the forge to create or import heroes!.
        /// </summary>
        public static string Msg_EmptyTavernHelp {
            get {
                return ResourceManager.GetString("Msg_EmptyTavernHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading character progression data....
        /// </summary>
        public static string Msg_LoadingProgression {
            get {
                return ResourceManager.GetString("Msg_LoadingProgression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No core traits registered..
        /// </summary>
        public static string Msg_NoCoreTraits {
            get {
                return ResourceManager.GetString("Msg_NoCoreTraits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This lineage has no exclusive traits..
        /// </summary>
        public static string Msg_NoLineageTraits {
            get {
                return ResourceManager.GetString("Msg_NoLineageTraits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rolls in this session yet....
        /// </summary>
        public static string Msg_NoRollsYet {
            get {
                return ResourceManager.GetString("Msg_NoRollsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending feats.
        /// </summary>
        public static string Msg_PendingFeats {
            get {
                return ResourceManager.GetString("Msg_PendingFeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending spells.
        /// </summary>
        public static string Msg_PendingSpells {
            get {
                return ResourceManager.GetString("Msg_PendingSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per level.
        /// </summary>
        public static string Msg_PerLevel {
            get {
                return ResourceManager.GetString("Msg_PerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore the lineages of the world....
        /// </summary>
        public static string Msg_SelectRacePrompt {
            get {
                return ResourceManager.GetString("Msg_SelectRacePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a spell for inspection.
        /// </summary>
        public static string Msg_SelectSpellToInspect {
            get {
                return ResourceManager.GetString("Msg_SelectSpellToInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summoning hero from the astral plane....
        /// </summary>
        public static string Msg_SummoningHero {
            get {
                return ResourceManager.GetString("Msg_SummoningHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature.
        /// </summary>
        public static string Nature {
            get {
                return ResourceManager.GetString("Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string NavCharacters {
            get {
                return ResourceManager.GetString("NavCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        public static string NavCreation {
            get {
                return ResourceManager.GetString("NavCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Dice.
        /// </summary>
        public static string NavDice {
            get {
                return ResourceManager.GetString("NavDice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string NavLibrary {
            get {
                return ResourceManager.GetString("NavLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed average hit points.
        /// </summary>
        public static string Option_FixedAverage {
            get {
                return ResourceManager.GetString("Option_FixedAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll hit points.
        /// </summary>
        public static string Option_RollDice {
            get {
                return ResourceManager.GetString("Option_RollDice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perception.
        /// </summary>
        public static string Perception {
            get {
                return ResourceManager.GetString("Perception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persuasion.
        /// </summary>
        public static string Persuasion {
            get {
                return ResourceManager.GetString("Persuasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the legend of your hero here....
        /// </summary>
        public static string Placeholder_History {
            get {
                return ResourceManager.GetString("Placeholder_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Alistair Ironfoot....
        /// </summary>
        public static string Placeholder_Name {
            get {
                return ResourceManager.GetString("Placeholder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search spell by name....
        /// </summary>
        public static string Placeholder_SearchSpell {
            get {
                return ResourceManager.GetString("Placeholder_SearchSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Throw Proficiencies.
        /// </summary>
        public static string Saving_Throws {
            get {
                return ResourceManager.GetString("Saving_Throws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select statistic placeholder.
        /// </summary>
        public static string Select_Stat {
            get {
                return ResourceManager.GetString("Select_Stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        public static string Shield {
            get {
                return ResourceManager.GetString("Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        public static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Proficiencies.
        /// </summary>
        public static string Skill_Proficiencies {
            get {
                return ResourceManager.GetString("Skill_Proficiencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleight of Hand.
        /// </summary>
        public static string Sleight_of_Hand {
            get {
                return ResourceManager.GetString("Sleight of Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantrip.
        /// </summary>
        public static string Spell_Cantrip {
            get {
                return ResourceManager.GetString("Spell_Cantrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Spell_Classes {
            get {
                return ResourceManager.GetString("Spell_Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Spell_Duration {
            get {
                return ResourceManager.GetString("Spell_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Spell_LevelText {
            get {
                return ResourceManager.GetString("Spell_LevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string Spell_Range {
            get {
                return ResourceManager.GetString("Spell_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell search.
        /// </summary>
        public static string Spell_Searcher {
            get {
                return ResourceManager.GetString("Spell_Searcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Spell_Time {
            get {
                return ResourceManager.GetString("Spell_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Action.
        /// </summary>
        public static string SpellCastTime__Action {
            get {
                return ResourceManager.GetString("SpellCastTime_ Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Action.
        /// </summary>
        public static string SpellCastTime_Action {
            get {
                return ResourceManager.GetString("SpellCastTime_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  BonusAction.
        /// </summary>
        public static string SpellCastTime_BonusAction {
            get {
                return ResourceManager.GetString("SpellCastTime_BonusAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hour.
        /// </summary>
        public static string SpellCastTime_Hour {
            get {
                return ResourceManager.GetString("SpellCastTime_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Minute.
        /// </summary>
        public static string SpellCastTime_Minute {
            get {
                return ResourceManager.GetString("SpellCastTime_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Reaction.
        /// </summary>
        public static string SpellCastTime_Reaction {
            get {
                return ResourceManager.GetString("SpellCastTime_Reaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Special.
        /// </summary>
        public static string SpellCastTime_Special {
            get {
                return ResourceManager.GetString("SpellCastTime_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Days.
        /// </summary>
        public static string SpellDuration__10Days {
            get {
                return ResourceManager.GetString("SpellDuration__10Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Minutes.
        /// </summary>
        public static string SpellDuration__10Minutes {
            get {
                return ResourceManager.GetString("SpellDuration__10Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Day.
        /// </summary>
        public static string SpellDuration__1Day {
            get {
                return ResourceManager.GetString("SpellDuration__1Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Hour.
        /// </summary>
        public static string SpellDuration__1Hour {
            get {
                return ResourceManager.GetString("SpellDuration__1Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Minute.
        /// </summary>
        public static string SpellDuration__1Minute {
            get {
                return ResourceManager.GetString("SpellDuration__1Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Round.
        /// </summary>
        public static string SpellDuration__1Round {
            get {
                return ResourceManager.GetString("SpellDuration__1Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 Hours.
        /// </summary>
        public static string SpellDuration__24Hours {
            get {
                return ResourceManager.GetString("SpellDuration__24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Days.
        /// </summary>
        public static string SpellDuration__30Days {
            get {
                return ResourceManager.GetString("SpellDuration__30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 Days.
        /// </summary>
        public static string SpellDuration__7Days {
            get {
                return ResourceManager.GetString("SpellDuration__7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 Hours.
        /// </summary>
        public static string SpellDuration__8Hours {
            get {
                return ResourceManager.GetString("SpellDuration__8Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration.
        /// </summary>
        public static string SpellDuration_Concentration {
            get {
                return ResourceManager.GetString("SpellDuration_Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantaneous.
        /// </summary>
        public static string SpellDuration_Instantaneous {
            get {
                return ResourceManager.GetString("SpellDuration_Instantaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent.
        /// </summary>
        public static string SpellDuration_Permanent {
            get {
                return ResourceManager.GetString("SpellDuration_Permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string SpellDuration_Special {
            get {
                return ResourceManager.GetString("SpellDuration_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until Dispelled.
        /// </summary>
        public static string SpellDuration_UntilDispelled {
            get {
                return ResourceManager.GetString("SpellDuration_UntilDispelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until Dispelled or Triggered.
        /// </summary>
        public static string SpellDuration_UntilDispelledOrTriggered {
            get {
                return ResourceManager.GetString("SpellDuration_UntilDispelledOrTriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 10 Minutes.
        /// </summary>
        public static string SpellDuration_UpTo10Minutes {
            get {
                return ResourceManager.GetString("SpellDuration_UpTo10Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 1 Day.
        /// </summary>
        public static string SpellDuration_UpTo1Day {
            get {
                return ResourceManager.GetString("SpellDuration_UpTo1Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 1 Hour.
        /// </summary>
        public static string SpellDuration_UpTo1Hour {
            get {
                return ResourceManager.GetString("SpellDuration_UpTo1Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 1 Minute.
        /// </summary>
        public static string SpellDuration_UpTo1Minute {
            get {
                return ResourceManager.GetString("SpellDuration_UpTo1Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 24 Hours.
        /// </summary>
        public static string SpellDuration_UpTo24Hours {
            get {
                return ResourceManager.GetString("SpellDuration_UpTo24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 2 Hours.
        /// </summary>
        public static string SpellDuration_UpTo2Hours {
            get {
                return ResourceManager.GetString("SpellDuration_UpTo2Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to 8 Hours.
        /// </summary>
        public static string SpellDuration_UpTo8Hours {
            get {
                return ResourceManager.GetString("SpellDuration_UpTo8Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        public static string SpellRange_Ranged {
            get {
                return ResourceManager.GetString("SpellRange_Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        public static string SpellRange_Self {
            get {
                return ResourceManager.GetString("SpellRange_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch.
        /// </summary>
        public static string SpellRange_Touch {
            get {
                return ResourceManager.GetString("SpellRange_Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Equipment.
        /// </summary>
        public static string Starting_Equipment {
            get {
                return ResourceManager.GetString("Starting_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        public static string Stat_Cha {
            get {
                return ResourceManager.GetString("Stat_Cha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        public static string Stat_Con {
            get {
                return ResourceManager.GetString("Stat_Con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Stat_Str {
            get {
                return ResourceManager.GetString("Stat_Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stealth.
        /// </summary>
        public static string Stealth {
            get {
                return ResourceManager.GetString("Stealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your legend begins with a single decision....
        /// </summary>
        public static string Subtitle_Creation {
            get {
                return ResourceManager.GetString("Subtitle_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival.
        /// </summary>
        public static string Survival {
            get {
                return ResourceManager.GetString("Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feats and Ability Score Improvement.
        /// </summary>
        public static string Tab_Feats_ASI {
            get {
                return ResourceManager.GetString("Tab_Feats_ASI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Tab_Features {
            get {
                return ResourceManager.GetString("Tab_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grimoire.
        /// </summary>
        public static string Tab_Grimoire {
            get {
                return ResourceManager.GetString("Tab_Grimoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Tab_Skills {
            get {
                return ResourceManager.GetString("Tab_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells management.
        /// </summary>
        public static string Tab_Spells {
            get {
                return ResourceManager.GetString("Tab_Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitals and Hit Points.
        /// </summary>
        public static string Tab_Vitals {
            get {
                return ResourceManager.GetString("Tab_Vitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Reference Table.
        /// </summary>
        public static string Table_Reference {
            get {
                return ResourceManager.GetString("Table_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Magic Energy.
        /// </summary>
        public static string Tip_AvailableSlot {
            get {
                return ResourceManager.GetString("Tip_AvailableSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expended Slot (Requires Long Rest).
        /// </summary>
        public static string Tip_ExpendedSlot {
            get {
                return ResourceManager.GetString("Tip_ExpendedSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim your pending rewards.
        /// </summary>
        public static string Title_ClaimPendingRewards {
            get {
                return ResourceManager.GetString("Title_ClaimPendingRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class and race features.
        /// </summary>
        public static string Title_ClassAndRaceFeatures {
            get {
                return ResourceManager.GetString("Title_ClassAndRaceFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Traits.
        /// </summary>
        public static string Title_CoreTraits {
            get {
                return ResourceManager.GetString("Title_CoreTraits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice Roller.
        /// </summary>
        public static string Title_DiceRoller {
            get {
                return ResourceManager.GetString("Title_DiceRoller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feat or Ability Score Improvement.
        /// </summary>
        public static string Title_FeatOrAsiSelection {
            get {
                return ResourceManager.GetString("Title_FeatOrAsiSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit points gained on level up.
        /// </summary>
        public static string Title_HitPointsGain {
            get {
                return ResourceManager.GetString("Title_HitPointsGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Up character.
        /// </summary>
        public static string Title_LevelUp {
            get {
                return ResourceManager.GetString("Title_LevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineage Features.
        /// </summary>
        public static string Title_LineageFeatures {
            get {
                return ResourceManager.GetString("Title_LineageFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineages &amp; Legacies.
        /// </summary>
        public static string Title_LineagesLegacies {
            get {
                return ResourceManager.GetString("Title_LineagesLegacies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Adventurers.
        /// </summary>
        public static string Title_MyAdventurers {
            get {
                return ResourceManager.GetString("Title_MyAdventurers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Hero.
        /// </summary>
        public static string Title_NewHero {
            get {
                return ResourceManager.GetString("Title_NewHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending selections.
        /// </summary>
        public static string Title_PendingSelections {
            get {
                return ResourceManager.GetString("Title_PendingSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your Path.
        /// </summary>
        public static string Title_SelectClass {
            get {
                return ResourceManager.GetString("Title_SelectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your Lineage.
        /// </summary>
        public static string Title_SelectRace {
            get {
                return ResourceManager.GetString("Title_SelectRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Title_Skills {
            get {
                return ResourceManager.GetString("Title_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellbook / Grimoire.
        /// </summary>
        public static string Title_Spellbook {
            get {
                return ResourceManager.GetString("Title_Spellbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells learning interface.
        /// </summary>
        public static string Title_SpellsLearning {
            get {
                return ResourceManager.GetString("Title_SpellsLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell slots.
        /// </summary>
        public static string Title_SpellSlots {
            get {
                return ResourceManager.GetString("Title_SpellSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Identity.
        /// </summary>
        public static string Title_StepIdentity {
            get {
                return ResourceManager.GetString("Title_StepIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Proficiencies.
        /// </summary>
        public static string Tools_Proficiencies {
            get {
                return ResourceManager.GetString("Tools_Proficiencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bardic Inspiration Die.
        /// </summary>
        public static string TraitType_BardicDie {
            get {
                return ResourceManager.GetString("TraitType_BardicDie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantrips Known.
        /// </summary>
        public static string TraitType_CantripsKnown {
            get {
                return ResourceManager.GetString("TraitType_CantripsKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Divinity.
        /// </summary>
        public static string TraitType_ChannelDivinityCount {
            get {
                return ResourceManager.GetString("TraitType_ChannelDivinityCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Divinity.
        /// </summary>
        public static string TraitType_ChannelDivinityUses {
            get {
                return ResourceManager.GetString("TraitType_ChannelDivinityUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favored Enemy.
        /// </summary>
        public static string TraitType_FavoredEnemyUses {
            get {
                return ResourceManager.GetString("TraitType_FavoredEnemyUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Points.
        /// </summary>
        public static string TraitType_FocusPoints {
            get {
                return ResourceManager.GetString("TraitType_FocusPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eldritch Invocations.
        /// </summary>
        public static string TraitType_InvocationsKnown {
            get {
                return ResourceManager.GetString("TraitType_InvocationsKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial Arts Die.
        /// </summary>
        public static string TraitType_MartialArtsDie {
            get {
                return ResourceManager.GetString("TraitType_MartialArtsDie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pact Magic Slots.
        /// </summary>
        public static string TraitType_PactSlots {
            get {
                return ResourceManager.GetString("TraitType_PactSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared Spells.
        /// </summary>
        public static string TraitType_PreparedSpellsCount {
            get {
                return ResourceManager.GetString("TraitType_PreparedSpellsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rage Damage.
        /// </summary>
        public static string TraitType_RageDamage {
            get {
                return ResourceManager.GetString("TraitType_RageDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rages.
        /// </summary>
        public static string TraitType_RagesCount {
            get {
                return ResourceManager.GetString("TraitType_RagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Wind.
        /// </summary>
        public static string TraitType_SecondWindUses {
            get {
                return ResourceManager.GetString("TraitType_SecondWindUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Level.
        /// </summary>
        public static string TraitType_SlotLevel {
            get {
                return ResourceManager.GetString("TraitType_SlotLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sneak Attack Die.
        /// </summary>
        public static string TraitType_SneakAttackDie {
            get {
                return ResourceManager.GetString("TraitType_SneakAttackDie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorcery Points.
        /// </summary>
        public static string TraitType_SorceryPoints {
            get {
                return ResourceManager.GetString("TraitType_SorceryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Slots.
        /// </summary>
        public static string TraitType_SpellSlots {
            get {
                return ResourceManager.GetString("TraitType_SpellSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unarmored Movement.
        /// </summary>
        public static string TraitType_UnarmoredMovement {
            get {
                return ResourceManager.GetString("TraitType_UnarmoredMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Masteries.
        /// </summary>
        public static string TraitType_WeaponMasteryCount {
            get {
                return ResourceManager.GetString("TraitType_WeaponMasteryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild Shape.
        /// </summary>
        public static string TraitType_WildShapeCount {
            get {
                return ResourceManager.GetString("TraitType_WildShapeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft..
        /// </summary>
        public static string Unit_Feet {
            get {
                return ResourceManager.GetString("Unit_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Proficiencies.
        /// </summary>
        public static string Weapon_Proficiencies {
            get {
                return ResourceManager.GetString("Weapon_Proficiencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom .
        /// </summary>
        public static string Wisdom {
            get {
                return ResourceManager.GetString("Wisdom", resourceCulture);
            }
        }
    }
}
